server:
  port: 8004        #8004表示注册到zookeeper服务器的支付微服务提供者端口号

# 服务别名  注册zookeeper服务中心名称
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 10.129.63.172:2181